
-- Create Feedback Table
create table if not exists app_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  pharmacy_id bigint references pharmacies(id), -- Optional connection to the visit
  reservation_id bigint, -- Optional connection to order
  pharmacy_rating integer,
  app_rating integer,
  suggestion text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Access Policies
alter table app_feedback enable row level security;

create policy "Users can insert their own feedback" 
on app_feedback for insert 
with check (auth.uid() = user_id);

-- Allow all authenticated users to view feedback (temporary fix for missing admins table)
create policy "Authenticated users can view feedback" 
on app_feedback for select 
using (auth.role() = 'authenticated');
