
-- 1. Create table for Customer Requests
create table if not exists medicine_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  customer_name text,
  drug_name text not null,
  latitude numeric not null,
  longitude numeric not null,
  status text default 'pending', -- 'pending', 'found', 'cancelled'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create table for Pharmacy Responses
create table if not exists pharmacy_responses (
  id bigint generated by default as identity primary key,
  request_id bigint references medicine_requests(id) on delete cascade not null,
  pharmacy_id bigint references pharmacies(id),
  pharmacy_name text,
  status text default 'available', -- 'available', 'not_available'
  price numeric,
  message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS
alter table medicine_requests enable row level security;
alter table pharmacy_responses enable row level security;

-- Policies for Requests
create policy "Requests viewable by everyone" on medicine_requests for select using (true);
create policy "Requests insertable by authenticated users" on medicine_requests for insert with check (auth.role() = 'authenticated');
create policy "Requests updatable by owner" on medicine_requests for update using (auth.uid() = user_id);

-- Policies for Responses
create policy "Responses viewable by everyone" on pharmacy_responses for select using (true);
create policy "Responses insertable by authenticated users" on pharmacy_responses for insert with check (auth.role() = 'authenticated');

-- 4. Enable Realtime (This is CRITICAL for the broadcast to work)
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table medicine_requests;
alter publication supabase_realtime add table pharmacy_responses;
