
-- Consolidated Script to Setup Broadcast and Location Features
-- Run this script in the Supabase SQL Editor to fix missing table errors

-- 1. Create table for Customer Requests (if not exists)
create table if not exists medicine_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  customer_name text,
  drug_name text not null,
  latitude numeric not null,
  longitude numeric not null,
  status text default 'pending', -- 'pending', 'found', 'cancelled'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create table for Pharmacy Responses (if not exists)
create table if not exists pharmacy_responses (
  id bigint generated by default as identity primary key,
  request_id bigint references medicine_requests(id) on delete cascade not null,
  pharmacy_id bigint references pharmacies(id),
  pharmacy_name text,
  status text default 'available', -- 'available', 'not_available'
  price numeric,
  message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS (safe to re-run)
alter table medicine_requests enable row level security;
alter table pharmacy_responses enable row level security;

-- Policies for Requests (Check existence to avoid error or drop/recreate)
do $$
begin
  if not exists (select from pg_policies where tablename = 'medicine_requests' and policyname = 'Requests viewable by everyone') then
    create policy "Requests viewable by everyone" on medicine_requests for select using (true);
  end if;
  
  if not exists (select from pg_policies where tablename = 'medicine_requests' and policyname = 'Requests insertable by authenticated users') then
    create policy "Requests insertable by authenticated users" on medicine_requests for insert with check (auth.role() = 'authenticated');
  end if;

  if not exists (select from pg_policies where tablename = 'medicine_requests' and policyname = 'Requests updatable by owner') then
    create policy "Requests updatable by owner" on medicine_requests for update using (auth.uid() = user_id);
  end if;
end $$;

-- Policies for Responses
do $$
begin
  if not exists (select from pg_policies where tablename = 'pharmacy_responses' and policyname = 'Responses viewable by everyone') then
    create policy "Responses viewable by everyone" on pharmacy_responses for select using (true);
  end if;

  if not exists (select from pg_policies where tablename = 'pharmacy_responses' and policyname = 'Responses insertable by authenticated users') then
    create policy "Responses insertable by authenticated users" on pharmacy_responses for insert with check (auth.role() = 'authenticated');
  end if;
end $$;

-- 4. Add location columns to pharmacy_responses (idempotent)
alter table pharmacy_responses 
add column if not exists pharmacy_lat numeric,
add column if not exists pharmacy_lng numeric;

-- 5. Enable Realtime (Drop publication first to avoid dupes)
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table medicine_requests;
alter publication supabase_realtime add table pharmacy_responses;

-- 6. Refresh Schema Cache
notify pgrst, 'reload schema';
