-- Create bed_reservations table
CREATE TABLE IF NOT EXISTS bed_reservations (
    id bigint generated by default as identity primary key,
    hospital_id uuid REFERENCES hospitals(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users,
    customer_name text,
    status text DEFAULT 'pending', -- pending, accepted, rejected, completed
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Relax RLS for hospital_appointments to allow customers to book
DROP POLICY IF EXISTS "Appointments viewable by hospital owner" ON hospital_appointments;
DROP POLICY IF EXISTS "Appointments insertable by hospital owner" ON hospital_appointments;
DROP POLICY IF EXISTS "Appointments updatable by hospital owner" ON hospital_appointments;
DROP POLICY IF EXISTS "Appointments deletable by hospital owner" ON hospital_appointments;

ALTER TABLE hospital_appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view appointments" ON hospital_appointments FOR SELECT USING (true);
CREATE POLICY "Everyone can book appointments" ON hospital_appointments FOR INSERT WITH CHECK (true);
CREATE POLICY "Hospitals can update their own appointments" ON hospital_appointments FOR UPDATE USING (auth.uid() = hospital_id);
CREATE POLICY "Hospitals can delete their own appointments" ON hospital_appointments FOR DELETE USING (auth.uid() = hospital_id);

-- Setup RLS for bed_reservations
ALTER TABLE bed_reservations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view bed reservations" ON bed_reservations FOR SELECT USING (true);
CREATE POLICY "Everyone can request beds" ON bed_reservations FOR INSERT WITH CHECK (true);
CREATE POLICY "Hospitals can update their own bed reservations" ON bed_reservations FOR UPDATE USING (auth.uid() = hospital_id);

-- Ensure hospitals can update their beds_occupied count
DROP POLICY IF EXISTS "Hospitals can be updated by owner" ON hospitals;
CREATE POLICY "Hospitals can be updated by owner" ON hospitals FOR UPDATE USING (auth.uid() = id);
