-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create profiles table (linked to auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  name text,
  role text check (role in ('customer', 'pharmacy', 'admin', 'hospital')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create drugs table
create table drugs (
  id bigint generated by default as identity primary key,
  name text not null,
  dosage text,
  type text,
  price numeric,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create pharmacies table
create table pharmacies (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  phone text,
  rating numeric default 0,
  owner_id uuid references auth.users, -- Link to a pharmacy user if needed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create inventory table
create table inventory (
  id bigint generated by default as identity primary key,
  pharmacy_id bigint references pharmacies(id) on delete cascade,
  drug_id bigint references drugs(id) on delete cascade,
  stock integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(pharmacy_id, drug_id)
);

-- Create reservations table
create table reservations (
  id bigint generated by default as identity primary key,
  pharmacy_id bigint references pharmacies(id),
  drug_id bigint references drugs(id),
  user_id uuid references auth.users,
  customer_name text,
  otp text,
  status text default 'pending', -- pending, completed, cancelled
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert initial Mock Data for Drugs
insert into drugs (name, dosage, type, price, description) values
('Amoxicillin', '500mg', 'Antibiotic', 15.00, 'Used to treat bacterial infections.'),
('Lisinopril', '10mg', 'Blood Pressure', 10.00, 'Used to treat high blood pressure.'),
('Metformin', '500mg', 'Diabetes', 8.00, 'Used to treat type 2 diabetes.'),
('Atorvastatin', '20mg', 'Cholesterol', 20.00, 'Used to lower cholesterol.'),
('Ibuprofen', '200mg', 'Pain Reliever', 5.00, 'Used to reduce fever and treat pain or inflammation.');

-- Insert initial Mock Data for Pharmacies
insert into pharmacies (name, address, phone) values
('HealthPlus Pharmacy', '123 Main St, New York, NY', '212-555-0123'),
('City Care Chemist', '456 Broadway, New York, NY', '212-555-0456'),
('MediQuick Rx', '789 5th Ave, New York, NY', '212-555-0789');

-- Insert initial Inventory
insert into inventory (pharmacy_id, drug_id, stock) values
(1, 1, 50), (1, 2, 30), (1, 5, 100),
(2, 1, 0), (2, 3, 45),
(3, 4, 20), (3, 5, 60);

-- Set up Row Level Security (RLS) - For demo purposes, we will allow public access to read/write
-- In a real app, you should restrict this!
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

alter table drugs enable row level security;
create policy "Drugs are viewable by everyone" on drugs for select using (true);

alter table pharmacies enable row level security;
create policy "Pharmacies are viewable by everyone" on pharmacies for select using (true);
create policy "Pharmacies can be created by pharmacy role" on pharmacies for insert with check (true); 

alter table inventory enable row level security;
create policy "Inventory is viewable by everyone" on inventory for select using (true);
create policy "Inventory can be updated by everyone (demo)" on inventory for update using (true);
create policy "Inventory can be inserted by everyone (demo)" on inventory for insert with check (true);

alter table reservations enable row level security;
create policy "Reservations are viewable by everyone (demo)" on reservations for select using (true);
create policy "Reservations can be inserted by everyone" on reservations for insert with check (true);
create policy "Reservations can be updated by everyone" on reservations for update using (true);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger 
language plpgsql 
security definer
set search_path = public, pg_temp, pg_catalog
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'role');
  
  -- Automatically create pharmacy record if role is pharmacy
  if (new.raw_user_meta_data->>'role' = 'pharmacy') then
    insert into public.pharmacies (name, owner_id, address, phone)
    values (new.raw_user_meta_data->>'name', new.id, 'Pending Address Update', 'Pending Phone');
  end if;

  return new;
end;
$$;

-- Create hospitals table
create table hospitals (
  id uuid references auth.users on delete cascade not null primary key,
  name text not null,
  address text,
  phone text,
  beds_total integer default 20,
  beds_occupied integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create hospital appointments table
create table hospital_appointments (
  id bigint generated by default as identity primary key,
  hospital_id uuid references hospitals(id) on delete cascade,
  patient_name text not null,
  scheduled_time timestamp with time zone not null,
  status text default 'scheduled', -- scheduled, completed, cancelled
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Hospitals
alter table hospitals enable row level security;
create policy "Hospitals are viewable by everyone" on hospitals for select using (true);
create policy "Hospitals can be updated by owner" on hospitals for update using (auth.uid() = id);

-- RLS for Appointments
alter table hospital_appointments enable row level security;
create policy "Appointments viewable by hospital owner" on hospital_appointments for select using (auth.uid() = hospital_id);
create policy "Appointments insertable by hospital owner" on hospital_appointments for insert with check (auth.uid() = hospital_id);
create policy "Appointments updatable by hospital owner" on hospital_appointments for update using (auth.uid() = hospital_id);
create policy "Appointments deletable by hospital owner" on hospital_appointments for delete using (auth.uid() = hospital_id);

-- Update handle_new_user to create hospital record
create or replace function public.handle_new_user()
returns trigger 
language plpgsql 
security definer
set search_path = public, pg_temp, pg_catalog
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'role');
  
  -- Automatically create pharmacy record if role is pharmacy
  if (new.raw_user_meta_data->>'role' = 'pharmacy') then
    insert into public.pharmacies (name, owner_id, address, phone)
    values (new.raw_user_meta_data->>'name', new.id, 'Pending Address Update', 'Pending Phone');
  end if;

  -- Automatically create hospital record if role is hospital
  if (new.raw_user_meta_data->>'role' = 'hospital') then
    insert into public.hospitals (id, name, address, phone)
    values (new.id, new.raw_user_meta_data->>'name', 'Pending Address', 'Pending Phone');
  end if;

  return new;
end;
$$;

-- Create emergency_requests table
create table emergency_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users, -- can be null for guest SOS?
  customer_name text,
  latitude numeric,
  longitude numeric,
  status text default 'pending', -- pending, dispatched, resolved
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Emergency Requests
alter table emergency_requests enable row level security;
create policy "Emergencies viewable by everyone (demo)" on emergency_requests for select using (true);
create policy "Emergencies insertable by everyone" on emergency_requests for insert with check (true);
create policy "Emergencies updatable by everyone" on emergency_requests for update using (true);

-- Admin Approval Columns
alter table public.pharmacies add column if not exists approved boolean default false;
alter table public.hospitals add column if not exists approved boolean default false;

-- Trigger to call the function on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
